--- 
- 
  name: "Checkmarx AST Github Action"
  uses: Checkmarx/ast-github-action@2.0.4
  with: 
    additional_params: "--tags test1 --scan-types sast --file-filter !readme --report-format sarif --output-name results"
    base_uri: "https://eu.ast.checkmarx.net/"
    branch: ~
    cx_client_id: LTI_AzureDevops_Oauth
    cx_client_secret: 4ffcfe5d-b7ed-40f2-ab95-dc097b64692d
    cx_tenant: nfr_acpl
    github_token: ~
    project_name: ~
- 
  name: "Upload SARIF file"
  uses: github/codeql-action/upload-sarif@v1
  with: 
    sarif_file: results.sarif
